### PR TITLE
MODELIX-1015 model-api-gen-gradle unusable in latest releases

### PR DESCRIPTION
**Pull request by mhuster23**
## To be verified by reviewers

* [ ] Relevant public API members have been documented
* [ ] Documentation related to this PR is complete
  * [ ] Boundary conditions are documented
  * [ ] Exceptions are documented
  * [ ] Nullability is documented if used
* [ ] Touched existing code has been extended with documentation if missing
* [ ] Code is readable
* [ ] New features and fixed bugs are covered by tests

### CODE REVIEW

**Comment by languitar** [comment]
Why wasn't this noticed by tests? Can we update the tests to somehow make this visible?

**Comment by mhuster23** [comment]
Our tests don't cover publication at all. In the past we published these locally and then used them in the test-projects, but we moved away from that since it was too easy to forget the core build or the `publishToMavenLocal` step and accidentally test the wrong version.

I'm not aware of plugins which can automatically validate the POM.

**Comment by languitar** [comment]
For verifying the overall functionality, we should have, at the highest level of the test pyramid, a real e2e test verifying that the integrated product is usable. This would have been caught that way. It would probably be enough to test this on main only and only in CI to cover these issues and to prevent automatic tagging on releases.

**Review by benedekh — APPROVED** [review]

**Pull request merged**
