### PR TITLE
fix(model-server): use one large transaction when putting many values

### PR DESCRIPTION
**Pull request by languitar**
So far, when putting multiple values via objects/put, a database transaction was created and committed for every value. That is unbelievably slow with a real database. This commit changes the implementation of the endpoint to use `putAll` instead of multiple `put` calls, effectively reducing the whole operation to a single transaction.

This is a `fix` commit and not a `perf` one as the previous implementation completely broke some known use cases due to ending in timeouts.

### CODE REVIEW

**Review by mhuster23 — APPROVED** [review]
This will use more memory as everything needs to be stored in the map first, but it's a tradeoff, that we probably have to make.

**Comment by languitar** [comment]
We could try to handle everything as a sequence as one further optimization. But that would also require extending the `IStoreClient` interface with a `putAll` version that accepts a stream of `Pair<String, String?>`.

**Comment by languitar** [comment]
That optimization won't work easily as the used IgniteCache only has an eager putAll signature.

**Comment by odzhychko** [comment]
> This will use more memory as everything needs to be stored in the map first, but it's a tradeoff, that we probably have to make.

> We could try to handle everything as a stream as one further optimization. But that would also require extending the IStoreClient interface with a putAll version that accepts a stream of Pair<String, String?>.

Have you looked into`IStoreClient.runTransaction`?
It does not work out of the box in the couroutine scope. But in general, that should be something doable.

**Comment by languitar** [comment]
`runTransaction` is used internally inside `put` and `putAll`. Just wrapping a `runTransaction` around many `put` calls already gave a speedup, but using `putAll` was still a lot faster and saturated the CPU more than just keeping the transaction alive.

**Pull request merged**
