### PR TITLE
 ci: use Renovate for updating pre-commmit dependencies

### PR DESCRIPTION
**Pull request by odzhychko**
Here you can see what updates Renovate would propose: https://github.com/odzhychko/modelix.core/pulls

## To be verified by reviewers

* [ ] Relevant public API members have been documented
* [ ] Documentation related to this PR is complete
  * [ ] Boundary conditions are documented
  * [ ] Exceptions are documented
  * [ ] Nullability is documented if used
* [ ] Touched existing code has been extended with documentation if missing
* [ ] Code is readable
* [ ] New features and fixed bugs are covered by tests

### CODE REVIEW

**Comment by languitar** [comment]
I'd propose to enable the dependency dashboard. That gives a good overview of what has been discovered etc: https://docs.renovatebot.com/key-concepts/dashboard/

**Comment by languitar** [comment]
Here's an example of how that looks like on GitHub: https://github.com/languitar/autosuspend/issues/131

**Comment by odzhychko** [comment]
> I'd propose to enable the dependency dashboard. That gives a good overview of what has been discovered etc: https://docs.renovatebot.com/key-concepts/dashboard/

https://docs.renovatebot.com/presets-config/

`config:best-practices` includes `config:recommended`.
`config:recommended` includes `:dependencyDashboard`.

**Comment by languitar** [comment]
Great, the dependency dashboard documentation page explicitly adds the dashboard alongside config:recomment :facepalm:

**Review by languitar — APPROVED** [review]

**Pull request merged**
