### PR TITLE
MODELIX-776 Automatically cast MonoSteps for newly created nodes

### PR DESCRIPTION
**Pull request by mhuster23**
see [MODELIX-776](https://issues.modelix.org/issue/MODELIX-776)

### CODE REVIEW

**Review by languitar — COMMENTED** [review]
Do you have an example of how the generated method now looks like?

**Comment by mhuster23** [comment]
Example of the now generated methods for the childlink `jetbrains.mps.baseLanguage.Classifier::method`.
```kotlin
public fun <Out : InstanceMethodDeclaration>
    IMonoStep<Classifier>.addToMethod(concept: IConceptOfTypedNode<Out>, index: Int = -1):
    IMonoStep<Out> = TypedModelQL.addNewChild(this, _C_UntypedImpl_Classifier.method, index,
    concept)

public fun IMonoStep<Classifier>.addToMethod(index: Int = -1): IMonoStep<InstanceMethodDeclaration>
    = TypedModelQL.addNewChild(this, _C_UntypedImpl_Classifier.method, index,
    C_InstanceMethodDeclaration)
```

**Review by languitar — COMMENTED** [review]
A bit unfortunate that the whole logic with `multiple` is duplicated. Maybe there's still a chance to reduce most things apart from the type parameter declaration.

**Review by languitar — APPROVED** [review]

**Pull request merged**
