### PR TITLE
Build/update versions

### PR DESCRIPTION
**Pull request by odzhychko**
Some versions are not updated by dependabot.

See. https://issues.modelix.org/issue/MODELIX-613/Collect-version-not-updated-by-dependabot

### CODE REVIEW

**Review by languitar — APPROVED** [review]

**Comment by languitar** [comment]
Probably needs a full reformatting run now

**Comment by odzhychko** [comment]
> Probably needs a full reformatting run now

I missed, that the default changed.
https://github.com/pinterest/ktlint/pull/2144

I will set it to the previous standard.

**Comment by odzhychko** [comment]
This PR was stale for a long time. It needs rebasing.

**Comment by odzhychko** [comment]
I am closing this stale PR.
I will create a new one after rebasing and reformatting.

**Pull request closed without merging**
