### PR TITLE
fix(modelql)!: disable implicit queries to avoid accidental performan…

### PR DESCRIPTION
**Pull request by slisson**

### CODE REVIEW

**Review by languitar — CHANGES_REQUESTED** [review]
Wouldn't it be a better idea to make the choice if implicit queries are allowed or not a constructor or builder argument of the client? That way, application can decide on a suitable configuration mechanism for them to apply.

Otherwise, the new option would need to be explained in the docs.

**Review by odzhychko — CHANGES_REQUESTED** [review]
The code and idea look good.
But the PR has two commits with the same message.

**Comment by odzhychko** [comment]
> Wouldn't it be a better idea to make the choice if implicit queries are allowed or not a constructor or builder argument of the client? That way, application can decide on a suitable configuration mechanism for them to apply.
> 
> Otherwise, the new option would need to be explained in the docs.

This would also allow clients to be configured differently in one application.

**Comment by slisson** [comment]
I was thinking about removing this feature completely, but didn't want to make switching to a new version unnecessarily difficult. A poor performance is still better than exceptions. Still not sure wether we should support this feature or deprecate it.

**Pull request closed without merging**
